// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Chat is the agent's conversation, read from the transcript rather than
 * scraped off the screen.
 * 
 * A pane shows what the agent drew. This shows what it said — and those are not
 * the same thing, because a TUI is a rendering: it wraps, truncates, redraws in
 * place and throws away everything that scrolled past. The transcript is the
 * record underneath, so a chat built from it can show a tool call the pane has
 * long since scrolled away, and can render a diff as a diff instead of as the
 * characters an agent chose to draw a diff with.
 * 
 * Claude Code writes it as JSON Lines under
 * ~/.claude/projects/<slug>/<session>.jsonl, and internal/watch already knows
 * how to find the newest one for a workspace — that package reads the same file
 * to follow the dev loop. What it does not have is this projection: it decodes
 * for gate and phase detection, with shapes unexported and tuned to that
 * question. Conversation turns are a different question about the same bytes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Follow watches the session's transcript and tells the frontend when it grows.
 * 
 * An event rather than the turns themselves: the file is appended to constantly
 * while an agent works, and pushing a parsed conversation on every write would
 * send the whole thing dozens of times a minute. The frontend re-reads when it
 * hears, which costs one parse per change and keeps the decision about how often
 * to look on the side that knows whether anyone is looking.
 * 
 * Polled rather than watched with fsevents. The transcript is a local file
 * appended by a process on the same machine; a second of latency is invisible
 * next to how long an agent takes to say anything, and a poll cannot leak a
 * watcher when the pane closes.
 */
export function Follow(session: string): $CancellablePromise<void> {
    return $Call.ByID(1658931763, session);
}

/**
 * Say sends a message to the agent as if it had been typed into its terminal.
 * 
 * Through `zmx paste` rather than by writing to the pty, and that is not a
 * detail: an agent's input is a line editor, so text arriving as a stream of
 * keystrokes gets interpreted — a newline submits, a bracket may trigger
 * completion, and a multi-line message would send itself one line at a time.
 * Paste wraps the text in bracketed-paste markers, which is how a terminal says
 * "this is text, not typing". awp already sends prompts this way; see
 * internal/cli/prompt_sender.go.
 * 
 * It also works with no pane attached, because it goes to the session rather
 * than through this client's pty — so the chat can be used on a workspace the
 * terminal tab has never been opened on.
 */
export function Say(session: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(293655465, session, text);
}

/**
 * Turns returns what the caller does not already have.
 * 
 * The whole conversation used to cross the bridge on every change, and the
 * change signal fires once a second while an agent works. A 7MB transcript
 * projects to megabytes of JSON, so the cost was not rendering it — it was
 * serialising it, shipping it, and parsing it again, sixty times a minute, to
 * deliver one new turn.
 * 
 * The cursor is a count rather than an id because the projection is a pure
 * function of the file: the first n turns of a longer read are the same n turns.
 * A count that no longer fits means the file was replaced, which is a reset
 * rather than an append.
 */
export function Turns(session: string, have: number): $CancellablePromise<$models.ChatSince> {
    return $Call.ByID(2583491866, session, have);
}

/**
 * Unfollow stops the watcher. Called when the chat is closed or the pane
 * switches away, so a session nobody is looking at is not being stat'd.
 */
export function Unfollow(): $CancellablePromise<void> {
    return $Call.ByID(2117338672);
}
