// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatTool is one tool call, and the result that came back for it.
 * 
 * Summary is the one line a collapsed row shows; Detail is what expanding it
 * reveals. They are separated here rather than in the frontend because deciding
 * what a Bash call is "about" means reading its arguments, and that is a
 * question about the tool's schema, not about layout.
 */
export interface ChatTool {
    "Name": string;
    "Summary": string;
    "Detail": string;
    "IsError": boolean;

    /**
     * File and Patch are set for edits, so the frontend can render a real diff
     * instead of the JSON arguments that produced one. The patch is built here
     * rather than shipped as two strings because turning an edit into a diff is
     * a question about the edit, not about how it is displayed.
     */
    "File": string;
    "Patch": string;
}

/**
 * ChatTurn is one entry in the conversation.
 */
export interface ChatTurn {
    /**
     * Kind is "user", "assistant" or "system".
     */
    "Kind": string;
    "At": string;
    "Text": string;
    "Thinking": string;
    "Tools": ChatTool[] | null;
}

/**
 * Workspace is one row of the sidebar: a workspace, and the agent in it.
 * 
 * The list is workspaces rather than sessions because a session is not what
 * anyone is looking for. `zmx ls` returns the editor beside the agent and calls
 * both a row, so a workspace being worked in appears twice and the list is
 * twice as long as the thing it describes. The deck's own list has always been
 * one row per workspace for the same reason.
 * 
 * Agent is the session a click attaches to, and is the only one a click ever
 * attaches to — an editor is nvim, and putting someone else's nvim in a pane is
 * not a thing this POC is asking about. A workspace whose agent has exited keeps
 * its row with Agent empty, because "this workspace has no agent right now" is
 * an answer, and silently dropping it would make the list disagree with the deck.
 */
export interface Workspace {
    "Project": string;
    "Workspace": string;

    /**
     * Agent is the zmx session name to attach to, or "" when there is none.
     */
    "Agent": string;

    /**
     * Cmd is what the agent is running, for the row's second line.
     */
    "Cmd": string;

    /**
     * Others counts the workspace's non-agent sessions, so the row can say the
     * editor is there without listing it as somewhere to go.
     */
    "Others": number;
}
