// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentStatus is what the agent is doing right now, from the store the deck's
 * status dots read.
 * 
 * The chat cannot answer this and never will: a transcript gains a line after
 * something finishes, so it is a record rather than a monitor. awp does not read
 * status from the transcript either — Claude Code hooks push it
 * (UserPromptSubmit, PreToolUse, Stop → `awp internal report-status`) into the
 * workspace store, which is event-driven and current. So the answer already
 * exists; it just was not being asked for here.
 */
export interface AgentStatus {
    /**
     * Status is awp's own vocabulary — "working", "waiting", "idle" and the
     * variants report-status writes. Left as written rather than normalised,
     * because internal/workspace.attention.go is where that vocabulary is
     * interpreted and a second interpretation here would drift from it.
     */
    "Status": string;

    /**
     * Prompt is the last thing the user asked, which is what the deck shows
     * beside a working row.
     */
    "Prompt": string;
    "Unread": boolean;
}

/**
 * ChatSince is the conversation from a point the caller already has.
 */
export interface ChatSince {
    /**
     * Total is how many turns exist, so the caller knows where it is up to.
     */
    "Total": number;

    /**
     * Turns are the ones after the caller's position, or all of them when the
     * transcript has been replaced.
     */
    "Turns": ChatTurn[] | null;

    /**
     * Reset says the caller should discard what it had: the count went
     * backwards, which means a different transcript, not more of this one.
     */
    "Reset": boolean;
}

/**
 * ChatTool is one tool call, and the result that came back for it.
 * 
 * Summary is the one line a collapsed row shows; Detail is what expanding it
 * reveals. They are separated here rather than in the frontend because deciding
 * what a Bash call is "about" means reading its arguments, and that is a
 * question about the tool's schema, not about layout.
 */
export interface ChatTool {
    "Name": string;
    "Summary": string;
    "Detail": string;
    "IsError": boolean;

    /**
     * File and Patch are set for edits, so the frontend can render a real diff
     * instead of the JSON arguments that produced one. The patch is built here
     * rather than shipped as two strings because turning an edit into a diff is
     * a question about the edit, not about how it is displayed.
     */
    "File": string;
    "Patch": string;
}

/**
 * ChatTurn is one entry in the conversation.
 */
export interface ChatTurn {
    /**
     * Kind is "user", "assistant" or "system".
     */
    "Kind": string;
    "At": string;
    "Text": string;
    "Thinking": string;
    "Tools": ChatTool[] | null;
}

/**
 * Workspace is one row of the sidebar: a workspace, and the agent in it.
 * 
 * The list is workspaces rather than sessions because a session is not what
 * anyone is looking for. `zmx ls` returns the editor beside the agent and calls
 * both a row, so a workspace being worked in appears twice and the list is
 * twice as long as the thing it describes. The deck's own list has always been
 * one row per workspace for the same reason.
 * 
 * Agent is the session a click attaches to, and is the only one a click ever
 * attaches to — an editor is nvim, and putting someone else's nvim in a pane is
 * not a thing this POC is asking about. A workspace whose agent has exited keeps
 * its row with Agent empty, because "this workspace has no agent right now" is
 * an answer, and silently dropping it would make the list disagree with the deck.
 */
export interface Workspace {
    "Project": string;
    "Workspace": string;

    /**
     * Agent is the zmx session name to attach to, or "" when there is none.
     */
    "Agent": string;

    /**
     * Cmd is what the agent is running, for the row's second line.
     */
    "Cmd": string;

    /**
     * Others counts the workspace's non-agent sessions, so the row can say the
     * editor is there without listing it as somewhere to go.
     */
    "Others": number;
}
