// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Workspace is one row of the sidebar: a workspace, and the agent in it.
 * 
 * The list is workspaces rather than sessions because a session is not what
 * anyone is looking for. `zmx ls` returns the editor beside the agent and calls
 * both a row, so a workspace being worked in appears twice and the list is
 * twice as long as the thing it describes. The deck's own list has always been
 * one row per workspace for the same reason.
 * 
 * Agent is the session a click attaches to, and is the only one a click ever
 * attaches to — an editor is nvim, and putting someone else's nvim in a pane is
 * not a thing this POC is asking about. A workspace whose agent has exited keeps
 * its row with Agent empty, because "this workspace has no agent right now" is
 * an answer, and silently dropping it would make the list disagree with the deck.
 */
export class Workspace {
    /**
     * Creates a new Workspace instance.
     * @param {Partial<Workspace>} [$$source = {}] - The source object to create the Workspace.
     */
    constructor($$source = {}) {
        if (!("Project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Project"] = "";
        }
        if (!("Workspace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Workspace"] = "";
        }
        if (!("Agent" in $$source)) {
            /**
             * Agent is the zmx session name to attach to, or "" when there is none.
             * @member
             * @type {string}
             */
            this["Agent"] = "";
        }
        if (!("Cmd" in $$source)) {
            /**
             * Cmd is what the agent is running, for the row's second line.
             * @member
             * @type {string}
             */
            this["Cmd"] = "";
        }
        if (!("Others" in $$source)) {
            /**
             * Others counts the workspace's non-agent sessions, so the row can say the
             * editor is there without listing it as somewhere to go.
             * @member
             * @type {number}
             */
            this["Others"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workspace instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Workspace}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Workspace(/** @type {Partial<Workspace>} */($$parsedSource));
    }
}
