// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Workspace is one row of the sidebar: a workspace, and the agent in it.
 * 
 * The list is workspaces rather than sessions because a session is not what
 * anyone is looking for. `zmx ls` returns the editor beside the agent and calls
 * both a row, so a workspace being worked in appears twice and the list is
 * twice as long as the thing it describes. The deck's own list has always been
 * one row per workspace for the same reason.
 * 
 * Agent is the session a click attaches to, and is the only one a click ever
 * attaches to — an editor is nvim, and putting someone else's nvim in a pane is
 * not a thing this POC is asking about. A workspace whose agent has exited keeps
 * its row with Agent empty, because "this workspace has no agent right now" is
 * an answer, and silently dropping it would make the list disagree with the deck.
 */
export interface Workspace {
    "Project": string;
    "Workspace": string;

    /**
     * Agent is the zmx session name to attach to, or "" when there is none.
     */
    "Agent": string;

    /**
     * Cmd is what the agent is running, for the row's second line.
     */
    "Cmd": string;

    /**
     * Others counts the workspace's non-agent sessions, so the row can say the
     * editor is there without listing it as somewhere to go.
     */
    "Others": number;
}
