// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Panes attaches the webview to a live zmx session.
 * 
 * The deck interprets a pane's bytes in Go — vterm.Hosted spawns the process,
 * libghostty-vt reads the pty, and the deck asks the result for a screen to put
 * in a layout. None of that happens here. The emulator is in the browser, so
 * this side is a pipe: bytes off the pty go up as events, keystrokes and resizes
 * come back down, and nothing in Go looks at what any of it means.
 * 
 * That is why this does not go through vterm.Hosted despite being the same job.
 * Hosted's whole surface is a terminal's answers — View, Cursor, CursorShape,
 * SelectionText — and a pipe has none of them to give. Reaching for it here
 * would mean running a second emulator in Go purely to discard its output.
 * 
 * One session at a time, deliberately. The POC is asking whether a pane feels
 * right, and a pane multiplexer is a different question that would have to be
 * answered again once the sidebar exists.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as zmx$0 from "../internal/zmx/models.js";

/**
 * Close ends the attach client. The session outlives it — that is the point of
 * zmx, and of not killing what the deck is only looking at.
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(1595534599);
}

/**
 * LaunchedFrom names the zmx session gdeck itself was started from, or "" when
 * it was not started from one.
 * 
 * Read before anything strips it, and offered to the frontend so that row can be
 * marked. Attaching to it is not a crash — vterm.Env keeps `zmx attach` from
 * hijacking the calling client — but it is still a second client on the terminal
 * the developer is sitting in, and the session will take gdeck's pane size. The
 * first thing a POC gets clicked on is whatever is at the top of the list.
 * @returns {$CancellablePromise<string>}
 */
export function LaunchedFrom() {
    return $Call.ByID(837023151);
}

/**
 * Open attaches to a session and starts streaming it. Any pane already open is
 * closed first — see the note on Panes about why there is only ever one.
 * 
 * Attaching is not read-only, and the POC should not pretend otherwise: a zmx
 * session takes its size from the client looking at it, so opening a pane
 * reflows the session's program to the pane's shape, and closing it reflows
 * again for whatever client is left. On an agent mid-answer that is visible and
 * unwelcome. Nothing here can avoid it — it is what attaching means — so the
 * frontend says so before the click rather than after.
 * @param {string} session
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Open(session, cols, rows) {
    return $Call.ByID(1045224821, session, cols, rows);
}

/**
 * Resize changes the pty's size, which is how the session learns its shape: a
 * zmx session takes its size from the client looking at it.
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(cols, rows) {
    return $Call.ByID(3944106949, cols, rows);
}

/**
 * Send writes base64-encoded bytes to the pane as if they had been typed.
 * @param {string} dataB64
 * @returns {$CancellablePromise<void>}
 */
export function Send(dataB64) {
    return $Call.ByID(964561067, dataB64);
}

/**
 * Sessions lists what zmx is holding, so the frontend has something real to
 * attach to.
 * @returns {$CancellablePromise<zmx$0.Session[]>}
 */
export function Sessions() {
    return $Call.ByID(167259848).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = zmx$0.Session.createFrom;
const $$createType1 = $Create.Array($$createType0);
