// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Panes attaches the webview to a live zmx session.
 * 
 * The deck interprets a pane's bytes in Go — vterm.Hosted spawns the process,
 * libghostty-vt reads the pty, and the deck asks the result for a screen to put
 * in a layout. None of that happens here. The emulator is in the browser, so
 * this side is a pipe: bytes off the pty go up as events, keystrokes and resizes
 * come back down, and nothing in Go looks at what any of it means.
 * 
 * That is why this does not go through vterm.Hosted despite being the same job.
 * Hosted's whole surface is a terminal's answers — View, Cursor, CursorShape,
 * SelectionText — and a pipe has none of them to give. Reaching for it here
 * would mean running a second emulator in Go purely to discard its output.
 * 
 * One session at a time, deliberately. The POC is asking whether a pane feels
 * right, and a pane multiplexer is a different question that would have to be
 * answered again once the sidebar exists.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close ends the attach client. The session outlives it — that is the point of
 * zmx, and of not killing what the deck is only looking at.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1595534599);
}

/**
 * History is what the session printed before this pane existed, escape
 * sequences intact, base64 for the same reason the live stream is.
 * 
 * A pane has no scrollback without it, and that is not a rendering bug however
 * much it looks like one: `zmx attach` replays the session's *current screen*,
 * so the wheel has nothing above the first frame to scroll to. `zmx history`
 * answers the other question — what came before — and the deck has never needed
 * to ask it, because a tmux or zmx client brings its own scrollback with it. A
 * webview terminal starts empty and has to be told.
 * 
 * Read without attaching, so nothing here resizes the session.
 */
export function History(session: string): $CancellablePromise<string> {
    return $Call.ByID(2477597723, session);
}

/**
 * Open attaches to a session and starts streaming it. Any pane already open is
 * closed first — see the note on Panes about why there is only ever one.
 * 
 * Attaching is not read-only, and the POC should not pretend otherwise: a zmx
 * session takes its size from the client looking at it, so opening a pane
 * reflows the session's program to the pane's shape, and closing it reflows
 * again for whatever client is left. On an agent mid-answer that is visible and
 * unwelcome. Nothing here can avoid it — it is what attaching means — so the
 * frontend says so before the click rather than after.
 */
export function Open(session: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(1045224821, session, cols, rows);
}

/**
 * Resize changes the pty's size, which is how the session learns its shape: a
 * zmx session takes its size from the client looking at it.
 */
export function Resize(cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3944106949, cols, rows);
}

/**
 * Send writes base64-encoded bytes to the pane as if they had been typed.
 */
export function Send(dataB64: string): $CancellablePromise<void> {
    return $Call.ByID(964561067, dataB64);
}

/**
 * Status reports the live state of the workspace a session belongs to.
 */
export function Status(project: string, workspace: string): $CancellablePromise<$models.AgentStatus> {
    return $Call.ByID(3422918283, project, workspace);
}

/**
 * Workspaces groups zmx's sessions into what the sidebar shows.
 * 
 * Derived from the sessions rather than from deckdata, which is the deck's own
 * view-model and the more complete answer: it knows workspaces that exist on
 * disk with nothing running in them at all, and it knows which of them want
 * attention. Neither is a question this POC asks — a pane needs something live
 * to attach to — so the cheaper source is the honest one until the sidebar has
 * to say more than "here is what you can open".
 */
export function Workspaces(): $CancellablePromise<$models.Workspace[] | null> {
    return $Call.ByID(625515787);
}
