// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Probe is how the frontend reports a POC result back to something that can be
 * read without a human looking at the window.
 * 
 * The questions this surface exists to answer are mostly answered in the
 * webview — wasm instantiates or it does not, a pane keeps up or it does not —
 * and the obvious way to check is to look at the screen. That does not survive
 * being run twice: nobody diffs two screenshots, and a result nobody recorded is
 * a result that gets remembered as better than it was. So each step reports
 * through here and the answer lands in gdeck's log next to the timings.
 * 
 * It is not a substitute for looking. Whether a pane *feels* right is exactly
 * the thing a pass/fail line cannot carry, which is why latency is reported as a
 * number rather than a verdict.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Report records the outcome of one POC check. detail carries the error when ok
 * is false, and whatever measurement the check produced when it is true.
 */
export function Report(check: string, ok: boolean, detail: string): $CancellablePromise<void> {
    return $Call.ByID(1046292212, check, ok, detail);
}

/**
 * Snapshot writes a PNG the frontend produced of its own canvas and returns the
 * path, so a layout can be checked without photographing the developer's screen.
 * 
 * A screen capture is the obvious way to see what a window looks like and the
 * wrong one: the frame contains whatever else was on the desktop — mail, chat,
 * another project's terminal — and none of that is the app's to collect. What is
 * actually being checked here is a canvas the pane drew, and a canvas can export
 * itself. So the image comes out of toDataURL and arrives here, bounded to
 * exactly the pixels gdeck rendered.
 * 
 * The name is validated rather than trusted. Nothing hostile is expected from
 * gdeck's own frontend, but this method turns a string from the webview into a
 * filesystem path, and that is the shape of a path traversal whoever writes the
 * next caller should not have to notice.
 */
export function Snapshot(check: string, dataURL: string): $CancellablePromise<string> {
    return $Call.ByID(300952938, check, dataURL);
}
