// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Session is one entry from `zmx ls`.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("PID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["PID"] = 0;
        }
        if (!("Clients" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Clients"] = 0;
        }
        if (!("StartDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["StartDir"] = "";
        }
        if (!("Ended" in $$source)) {
            /**
             * Ended is true once the session's command has exited. zmx keeps the
             * session listed afterwards so its output can still be read, so "listed"
             * and "running" are different questions.
             * @member
             * @type {boolean}
             */
            this["Ended"] = false;
        }
        if (!("ExitCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ExitCode"] = 0;
        }
        if (!("Created" in $$source)) {
            /**
             * Created is when zmx started the session, and Cmd the command it is
             * running. Both are only interesting to something displaying the session
             * to a human — `zmx ls` prints created as a unix stamp, which is not a
             * thing to show anyone.
             * @member
             * @type {string}
             */
            this["Created"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("Cmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Cmd"] = "";
        }
        if (!("Labels" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["Labels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField8_0($$parsedSource["Labels"]);
        }
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
